In [1]:
import requests
import pandas as pd
import hvplot.pandas
from dotenv import load_dotenv
import os
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut
import time
import numpy as np
load_dotenv()

True

In [2]:

r = requests.get("https://api.census.gov/data/timeseries/intltrade/imports/hs?get=CTY_NAME,CTY_CODE,GEN_VAL_YR&time=2013-12&key=4b47fff787a4802c4e94f1d177840dd265a548f8")
data = r.json()

#fix the columns
us_ports_imports_by_cty_2013 = pd.DataFrame(data)
us_ports_imports_by_cty_2013.columns = us_ports_imports_by_cty_2013.iloc[0]
us_ports_imports_by_cty_2013 = us_ports_imports_by_cty_2013[1:]

us_ports_imports_by_cty_2013 = us_ports_imports_by_cty_2013.rename(columns={'GEN_VAL_YR': 'ALL_VAL_YR'})
us_ports_imports_by_cty_2013.set_index('CTY_NAME', inplace=True)

us_ports_imports_by_cty_2013

0                 CTY_CODE ALL_VAL_YR     time
CTY_NAME
NEW CALEDONIA         6412   69561109  2013-12
WALLIS AND FUTUNA     6413     296015  2013-12
FRENCH POLYNESIA      6414   36492874  2013-12
MARSHALL ISLANDS      6810   16965963  2013-12
MICRONESIA            6820    1786725  2013-12
...                    ...        ...      ...
SOLOMON ISLANDS       6223    8841794  2013-12
VANUATU               6224    4192881  2013-12
PITCAIRN ISLANDS      6225       3439  2013-12
KIRIBATI              6226    1020432  2013-12
TUVALU                6227      34138  2013-12

[253 rows x 3 columns]

In [3]:

r = requests.get("https://api.census.gov/data/timeseries/intltrade/imports/hs?get=CTY_NAME,CTY_CODE,GEN_VAL_YR&time=2014-12&key=4b47fff787a4802c4e94f1d177840dd265a548f8")
data = r.json()

us_ports_imports_by_cty_2014 = pd.DataFrame(data)
us_ports_imports_by_cty_2014.columns = us_ports_imports_by_cty_2014.iloc[0]
us_ports_imports_by_cty_2014 = us_ports_imports_by_cty_2014[1:]

us_ports_imports_by_cty_2014 = us_ports_imports_by_cty_2014.rename(columns={'GEN_VAL_YR': 'ALL_VAL_YR'})
us_ports_imports_by_cty_2014.set_index('CTY_NAME', inplace=True)
us_ports_imports_by_cty_2014.tail()

0        CTY_CODE ALL_VAL_YR     time
CTY_NAME
ZAMBIA       7940   55669752  2014-12
ESWATINI     7950   81649559  2014-12
ZIMBABWE     7960   64644521  2014-12
MALAWI       7970   66590802  2014-12
LESOTHO      7990  361092405  2014-12

In [4]:
r = requests.get("https://api.census.gov/data/timeseries/intltrade/imports/hs?get=CTY_NAME,CTY_CODE,GEN_VAL_YR&time=2015-12&key=4b47fff787a4802c4e94f1d177840dd265a548f8")
data = r.json()

us_ports_imports_by_cty_2015 = pd.DataFrame(data)
us_ports_imports_by_cty_2015.columns = us_ports_imports_by_cty_2015.iloc[0]
us_ports_imports_by_cty_2015 = us_ports_imports_by_cty_2015[1:]

us_ports_imports_by_cty_2015 = us_ports_imports_by_cty_2015.rename(columns={'GEN_VAL_YR': 'ALL_VAL_YR'})
us_ports_imports_by_cty_2015.set_index('CTY_NAME', inplace=True)
us_ports_imports_by_cty_2015.tail()

0                       CTY_CODE     ALL_VAL_YR     time
CTY_NAME
CAMEROON                    7420      132107808  2015-12
SENEGAL                     7440       71965108  2015-12
MALI                        7450        4522941  2015-12
GUINEA                      7460       79616516  2015-12
TOTAL FOR ALL COUNTRIES        -  2248811351481  2015-12

In [5]:

r = requests.get("https://api.census.gov/data/timeseries/intltrade/imports/hs?get=CTY_NAME,CTY_CODE,GEN_VAL_YR&time=2016-12&key=4b47fff787a4802c4e94f1d177840dd265a548f8")
data = r.json()

us_ports_imports_by_cty_2016 = pd.DataFrame(data)
us_ports_imports_by_cty_2016.columns = us_ports_imports_by_cty_2016.iloc[0]
us_ports_imports_by_cty_2016 = us_ports_imports_by_cty_2016[1:]

us_ports_imports_by_cty_2016 = us_ports_imports_by_cty_2016.rename(columns={'GEN_VAL_YR': 'ALL_VAL_YR'})
us_ports_imports_by_cty_2016.set_index('CTY_NAME', inplace=True)

us_ports_imports_by_cty_2016.tail()

0        CTY_CODE   ALL_VAL_YR     time
CTY_NAME
ESWATINI     7950     16993425  2016-12
ZIMBABWE     7960     23490633  2016-12
MALAWI       7970     74401986  2016-12
LESOTHO      7990    310466933  2016-12
AFRICA       7XXX  26556310776  2016-12

In [6]:

r = requests.get("https://api.census.gov/data/timeseries/intltrade/imports/hs?get=CTY_NAME,CTY_CODE,GEN_VAL_YR&time=2017-12&key=4b47fff787a4802c4e94f1d177840dd265a548f8")
data = r.json()

us_ports_imports_by_cty_2017 = pd.DataFrame(data)
us_ports_imports_by_cty_2017.columns = us_ports_imports_by_cty_2017.iloc[0]
us_ports_imports_by_cty_2017 = us_ports_imports_by_cty_2017[1:]

us_ports_imports_by_cty_2017 = us_ports_imports_by_cty_2017.rename(columns={'GEN_VAL_YR': 'ALL_VAL_YR'})
us_ports_imports_by_cty_2017.set_index('CTY_NAME', inplace=True)

us_ports_imports_by_cty_2017.tail()

0        CTY_CODE   ALL_VAL_YR     time
CTY_NAME
ESWATINI     7950     20460460  2017-12
ZIMBABWE     7960     47296407  2017-12
MALAWI       7970     61885801  2017-12
LESOTHO      7990    308335090  2017-12
AFRICA       7XXX  33410089495  2017-12

In [7]:
time = '2012-12'

r = requests.get("https://api.census.gov/data/timeseries/intltrade/imports/hs?get=CTY_NAME,CTY_CODE,GEN_VAL_YR&time=2018-12&key=4b47fff787a4802c4e94f1d177840dd265a548f8")
data = r.json()

us_ports_imports_by_cty_2018 = pd.DataFrame(data)
us_ports_imports_by_cty_2018.columns = us_ports_imports_by_cty_2018.iloc[0]
us_ports_imports_by_cty_2018 = us_ports_imports_by_cty_2018[1:]

us_ports_imports_by_cty_2018 = us_ports_imports_by_cty_2018.rename(columns={'GEN_VAL_YR': 'ALL_VAL_YR'})
us_ports_imports_by_cty_2018.set_index('CTY_NAME', inplace=True)

us_ports_imports_by_cty_2018.tail()

0        CTY_CODE   ALL_VAL_YR     time
CTY_NAME
ESWATINI     7950     13319542  2018-12
ZIMBABWE     7960     75428482  2018-12
MALAWI       7970     57484697  2018-12
LESOTHO      7990    421684032  2018-12
AFRICA       7XXX  35808203173  2018-12

In [8]:
r = requests.get("https://api.census.gov/data/timeseries/intltrade/imports/hs?get=CTY_NAME,CTY_CODE,GEN_VAL_YR&time=2019-12&key=4b47fff787a4802c4e94f1d177840dd265a548f8")
data = r.json()

us_ports_imports_by_cty_2019 = pd.DataFrame(data)
us_ports_imports_by_cty_2019.columns = us_ports_imports_by_cty_2019.iloc[0]
us_ports_imports_by_cty_2019 = us_ports_imports_by_cty_2019[1:]

us_ports_imports_by_cty_2019 = us_ports_imports_by_cty_2019.rename(columns={'GEN_VAL_YR': 'ALL_VAL_YR'})
us_ports_imports_by_cty_2019.set_index('CTY_NAME', inplace=True)

us_ports_imports_by_cty_2019.tail()

0        CTY_CODE   ALL_VAL_YR     time
CTY_NAME
ESWATINI     7950     15871409  2019-12
ZIMBABWE     7960     47041815  2019-12
MALAWI       7970     79469352  2019-12
LESOTHO      7990    324951576  2019-12
AFRICA       7XXX  30166603587  2019-12

In [9]:
r = requests.get("https://api.census.gov/data/timeseries/intltrade/imports/hs?get=CTY_NAME,CTY_CODE,GEN_VAL_YR&time=2020-12&key=4b47fff787a4802c4e94f1d177840dd265a548f8")
data = r.json()

us_ports_imports_by_cty_2020 = pd.DataFrame(data)
us_ports_imports_by_cty_2020.columns = us_ports_imports_by_cty_2020.iloc[0]
us_ports_imports_by_cty_2020 = us_ports_imports_by_cty_2020[1:]

us_ports_imports_by_cty_2020 = us_ports_imports_by_cty_2020.rename(columns={'GEN_VAL_YR': 'ALL_VAL_YR'})
us_ports_imports_by_cty_2020.set_index('CTY_NAME', inplace=True)

us_ports_imports_by_cty_2020.tail()

0        CTY_CODE   ALL_VAL_YR     time
CTY_NAME
ESWATINI     7950     19516027  2020-12
ZIMBABWE     7960     36856066  2020-12
MALAWI       7970     43247962  2020-12
LESOTHO      7990    305074164  2020-12
AFRICA       7XXX  23731778955  2020-12

In [10]:
r = requests.get("https://api.census.gov/data/timeseries/intltrade/imports/hs?get=CTY_NAME,CTY_CODE,GEN_VAL_YR&time=2021-12&key=4b47fff787a4802c4e94f1d177840dd265a548f8")
data = r.json()

us_ports_imports_by_cty_2021 = pd.DataFrame(data)
us_ports_imports_by_cty_2021.columns = us_ports_imports_by_cty_2021.iloc[0]
us_ports_imports_by_cty_2021 = us_ports_imports_by_cty_2021[1:]

us_ports_imports_by_cty_2021 = us_ports_imports_by_cty_2021.rename(columns={'GEN_VAL_YR': 'ALL_VAL_YR'})
us_ports_imports_by_cty_2021.set_index('CTY_NAME', inplace=True)

us_ports_imports_by_cty_2021.tail()

0        CTY_CODE   ALL_VAL_YR     time
CTY_NAME
ESWATINI     7950     23490900  2021-12
ZIMBABWE     7960     42792421  2021-12
MALAWI       7970     48027952  2021-12
LESOTHO      7990    333305609  2021-12
AFRICA       7XXX  37626076262  2021-12

In [11]:
time = '2012-12'

r = requests.get("https://api.census.gov/data/timeseries/intltrade/imports/hs?get=CTY_NAME,CTY_CODE,GEN_VAL_YR&time=2022-12&key=4b47fff787a4802c4e94f1d177840dd265a548f8")
data = r.json()

us_ports_imports_by_cty_2022 = pd.DataFrame(data)
us_ports_imports_by_cty_2022.columns = us_ports_imports_by_cty_2022.iloc[0]
us_ports_imports_by_cty_2022 = us_ports_imports_by_cty_2022[1:]

us_ports_imports_by_cty_2022 = us_ports_imports_by_cty_2022.rename(columns={'GEN_VAL_YR': 'ALL_VAL_YR'})
us_ports_imports_by_cty_2022.set_index('CTY_NAME', inplace=True)


us_ports_imports_by_cty_2022.tail(100)

0           CTY_CODE   ALL_VAL_YR     time
CTY_NAME
TIMOR-LESTE     5601     10439867  2022-12
BRUNEI          5610     90404897  2022-12
PHILIPPINES     5650  16155367940  2022-12
MACAU           5660    161992524  2022-12
BHUTAN          5682       291764  2022-12
...              ...          ...      ...
ESWATINI        7950     22435037  2022-12
ZIMBABWE        7960     86509488  2022-12
MALAWI          7970     54005871  2022-12
LESOTHO         7990    349542302  2022-12
AFRICA          7XXX  41815621740  2022-12

[100 rows x 3 columns]

In [12]:
#clean up

#2013
us_ports_imports_by_cty_2013 = us_ports_imports_by_cty_2013.drop(index = ["OECD"])
us_ports_imports_by_cty_2013= us_ports_imports_by_cty_2013.drop(index = ["ASIA"])
us_ports_imports_by_cty_2013= us_ports_imports_by_cty_2013.drop(index = ["PACIFIC RIM COUNTRIES"])   
us_ports_imports_by_cty_2013= us_ports_imports_by_cty_2013.drop(index = ["NATO"])
us_ports_imports_by_cty_2013= us_ports_imports_by_cty_2013.drop(index = ["NORTH AMERICA"])
us_ports_imports_by_cty_2013= us_ports_imports_by_cty_2013.drop(index = ["NAFTA"])
us_ports_imports_by_cty_2013= us_ports_imports_by_cty_2013.drop(index = ["EUROPE"])
us_ports_imports_by_cty_2013= us_ports_imports_by_cty_2013.drop(index = ["TWENTY LATIN AMERICAN REPUBLICS"])
us_ports_imports_by_cty_2013= us_ports_imports_by_cty_2013.drop(index = ["LAFTA"])
us_ports_imports_by_cty_2013= us_ports_imports_by_cty_2013.drop(index = ["EUROPEAN UNION"])
us_ports_imports_by_cty_2013= us_ports_imports_by_cty_2013.drop(index = ["EURO AREA"])
us_ports_imports_by_cty_2013= us_ports_imports_by_cty_2013.drop(index = ["OPEC"])
us_ports_imports_by_cty_2013= us_ports_imports_by_cty_2013.drop(index = ["ASEAN"])
us_ports_imports_by_cty_2013= us_ports_imports_by_cty_2013.drop(index = ["SOUTH AMERICA"])
us_ports_imports_by_cty_2013= us_ports_imports_by_cty_2013.drop(index = ["AFRICA"])
us_ports_imports_by_cty_2013= us_ports_imports_by_cty_2013.drop(index = ["CENTRAL AMERICA"])
us_ports_imports_by_cty_2013= us_ports_imports_by_cty_2013.drop(index = ["APEC"])
us_ports_imports_by_cty_2013= us_ports_imports_by_cty_2013.drop(index = ["TOTAL FOR ALL COUNTRIES"])

#2014
us_ports_imports_by_cty_2014 = us_ports_imports_by_cty_2014.drop(index = ["OECD"])
us_ports_imports_by_cty_2014= us_ports_imports_by_cty_2014.drop(index = ["ASIA"])
us_ports_imports_by_cty_2014= us_ports_imports_by_cty_2014.drop(index = ["PACIFIC RIM COUNTRIES"])   
us_ports_imports_by_cty_2014= us_ports_imports_by_cty_2014.drop(index = ["NATO"])
us_ports_imports_by_cty_2014= us_ports_imports_by_cty_2014.drop(index = ["NORTH AMERICA"])
us_ports_imports_by_cty_2014= us_ports_imports_by_cty_2014.drop(index = ["NAFTA"])
us_ports_imports_by_cty_2014= us_ports_imports_by_cty_2014.drop(index = ["EUROPE"])
us_ports_imports_by_cty_2014= us_ports_imports_by_cty_2014.drop(index = ["TWENTY LATIN AMERICAN REPUBLICS"])
us_ports_imports_by_cty_2014= us_ports_imports_by_cty_2014.drop(index = ["LAFTA"])
us_ports_imports_by_cty_2014= us_ports_imports_by_cty_2014.drop(index = ["EUROPEAN UNION"])
us_ports_imports_by_cty_2014= us_ports_imports_by_cty_2014.drop(index = ["EURO AREA"])
us_ports_imports_by_cty_2014= us_ports_imports_by_cty_2014.drop(index = ["OPEC"])
us_ports_imports_by_cty_2014= us_ports_imports_by_cty_2014.drop(index = ["ASEAN"])
us_ports_imports_by_cty_2014= us_ports_imports_by_cty_2014.drop(index = ["SOUTH AMERICA"])
us_ports_imports_by_cty_2014= us_ports_imports_by_cty_2014.drop(index = ["AFRICA"])
us_ports_imports_by_cty_2014= us_ports_imports_by_cty_2014.drop(index = ["CENTRAL AMERICA"])
us_ports_imports_by_cty_2014= us_ports_imports_by_cty_2014.drop(index = ["APEC"])
us_ports_imports_by_cty_2014= us_ports_imports_by_cty_2014.drop(index = ["TOTAL FOR ALL COUNTRIES"])

#2015
us_ports_imports_by_cty_2015 = us_ports_imports_by_cty_2015.drop(index = ["OECD"])
us_ports_imports_by_cty_2015= us_ports_imports_by_cty_2015.drop(index = ["ASIA"])
us_ports_imports_by_cty_2015= us_ports_imports_by_cty_2015.drop(index = ["PACIFIC RIM COUNTRIES"])   
us_ports_imports_by_cty_2015= us_ports_imports_by_cty_2015.drop(index = ["NATO"])
us_ports_imports_by_cty_2015= us_ports_imports_by_cty_2015.drop(index = ["NORTH AMERICA"])
us_ports_imports_by_cty_2015= us_ports_imports_by_cty_2015.drop(index = ["NAFTA"])
us_ports_imports_by_cty_2015= us_ports_imports_by_cty_2015.drop(index = ["EUROPE"])
us_ports_imports_by_cty_2015= us_ports_imports_by_cty_2015.drop(index = ["TWENTY LATIN AMERICAN REPUBLICS"])
us_ports_imports_by_cty_2015= us_ports_imports_by_cty_2015.drop(index = ["LAFTA"])
us_ports_imports_by_cty_2015= us_ports_imports_by_cty_2015.drop(index = ["EUROPEAN UNION"])
us_ports_imports_by_cty_2015= us_ports_imports_by_cty_2015.drop(index = ["EURO AREA"])
us_ports_imports_by_cty_2015= us_ports_imports_by_cty_2015.drop(index = ["OPEC"])
us_ports_imports_by_cty_2015= us_ports_imports_by_cty_2015.drop(index = ["ASEAN"])
us_ports_imports_by_cty_2015= us_ports_imports_by_cty_2015.drop(index = ["SOUTH AMERICA"])
us_ports_imports_by_cty_2015= us_ports_imports_by_cty_2015.drop(index = ["AFRICA"])
us_ports_imports_by_cty_2015= us_ports_imports_by_cty_2015.drop(index = ["CENTRAL AMERICA"])
us_ports_imports_by_cty_2015= us_ports_imports_by_cty_2015.drop(index = ["APEC"])
us_ports_imports_by_cty_2015= us_ports_imports_by_cty_2015.drop(index = ["TOTAL FOR ALL COUNTRIES"])

#2016
us_ports_imports_by_cty_2016 = us_ports_imports_by_cty_2016.drop(index = ["OECD"])
us_ports_imports_by_cty_2016= us_ports_imports_by_cty_2016.drop(index = ["ASIA"])
us_ports_imports_by_cty_2016= us_ports_imports_by_cty_2016.drop(index = ["PACIFIC RIM COUNTRIES"])   
us_ports_imports_by_cty_2016= us_ports_imports_by_cty_2016.drop(index = ["NATO"])
us_ports_imports_by_cty_2016= us_ports_imports_by_cty_2016.drop(index = ["NORTH AMERICA"])
us_ports_imports_by_cty_2016= us_ports_imports_by_cty_2016.drop(index = ["NAFTA"])
us_ports_imports_by_cty_2016= us_ports_imports_by_cty_2016.drop(index = ["EUROPE"])
us_ports_imports_by_cty_2016= us_ports_imports_by_cty_2016.drop(index = ["TWENTY LATIN AMERICAN REPUBLICS"])
us_ports_imports_by_cty_2016= us_ports_imports_by_cty_2016.drop(index = ["LAFTA"])
us_ports_imports_by_cty_2016= us_ports_imports_by_cty_2016.drop(index = ["EUROPEAN UNION"])
us_ports_imports_by_cty_2016= us_ports_imports_by_cty_2016.drop(index = ["EURO AREA"])
us_ports_imports_by_cty_2016= us_ports_imports_by_cty_2016.drop(index = ["OPEC"])
us_ports_imports_by_cty_2016= us_ports_imports_by_cty_2016.drop(index = ["ASEAN"])
us_ports_imports_by_cty_2016= us_ports_imports_by_cty_2016.drop(index = ["SOUTH AMERICA"])
us_ports_imports_by_cty_2016= us_ports_imports_by_cty_2016.drop(index = ["AFRICA"])
us_ports_imports_by_cty_2016= us_ports_imports_by_cty_2016.drop(index = ["CENTRAL AMERICA"])
us_ports_imports_by_cty_2016= us_ports_imports_by_cty_2016.drop(index = ["APEC"])
us_ports_imports_by_cty_2016= us_ports_imports_by_cty_2016.drop(index = ["TOTAL FOR ALL COUNTRIES"])

#2017
us_ports_imports_by_cty_2017 = us_ports_imports_by_cty_2017.drop(index = ["OECD"])
us_ports_imports_by_cty_2017= us_ports_imports_by_cty_2017.drop(index = ["ASIA"])
us_ports_imports_by_cty_2017= us_ports_imports_by_cty_2017.drop(index = ["PACIFIC RIM COUNTRIES"])   
us_ports_imports_by_cty_2017= us_ports_imports_by_cty_2017.drop(index = ["NATO"])
us_ports_imports_by_cty_2017= us_ports_imports_by_cty_2017.drop(index = ["NORTH AMERICA"])
us_ports_imports_by_cty_2017= us_ports_imports_by_cty_2017.drop(index = ["NAFTA"])
us_ports_imports_by_cty_2017= us_ports_imports_by_cty_2017.drop(index = ["EUROPE"])
us_ports_imports_by_cty_2017= us_ports_imports_by_cty_2017.drop(index = ["TWENTY LATIN AMERICAN REPUBLICS"])
us_ports_imports_by_cty_2017= us_ports_imports_by_cty_2017.drop(index = ["LAFTA"])
us_ports_imports_by_cty_2017= us_ports_imports_by_cty_2017.drop(index = ["EUROPEAN UNION"])
us_ports_imports_by_cty_2017= us_ports_imports_by_cty_2017.drop(index = ["EURO AREA"])
us_ports_imports_by_cty_2017= us_ports_imports_by_cty_2017.drop(index = ["OPEC"])
us_ports_imports_by_cty_2017= us_ports_imports_by_cty_2017.drop(index = ["ASEAN"])
us_ports_imports_by_cty_2017= us_ports_imports_by_cty_2017.drop(index = ["SOUTH AMERICA"])
us_ports_imports_by_cty_2017= us_ports_imports_by_cty_2017.drop(index = ["AFRICA"])
us_ports_imports_by_cty_2017= us_ports_imports_by_cty_2017.drop(index = ["CENTRAL AMERICA"])
us_ports_imports_by_cty_2017= us_ports_imports_by_cty_2017.drop(index = ["APEC"])
us_ports_imports_by_cty_2017= us_ports_imports_by_cty_2017.drop(index = ["TOTAL FOR ALL COUNTRIES"])

#2018
us_ports_imports_by_cty_2018 = us_ports_imports_by_cty_2018.drop(index = ["OECD"])
us_ports_imports_by_cty_2018= us_ports_imports_by_cty_2018.drop(index = ["ASIA"])
us_ports_imports_by_cty_2018= us_ports_imports_by_cty_2018.drop(index = ["PACIFIC RIM COUNTRIES"])   
us_ports_imports_by_cty_2018= us_ports_imports_by_cty_2018.drop(index = ["NATO"])
us_ports_imports_by_cty_2018= us_ports_imports_by_cty_2018.drop(index = ["NORTH AMERICA"])
us_ports_imports_by_cty_2018= us_ports_imports_by_cty_2018.drop(index = ["NAFTA"])
us_ports_imports_by_cty_2018= us_ports_imports_by_cty_2018.drop(index = ["EUROPE"])
us_ports_imports_by_cty_2018= us_ports_imports_by_cty_2018.drop(index = ["TWENTY LATIN AMERICAN REPUBLICS"])
us_ports_imports_by_cty_2018= us_ports_imports_by_cty_2018.drop(index = ["LAFTA"])
us_ports_imports_by_cty_2018= us_ports_imports_by_cty_2018.drop(index = ["EUROPEAN UNION"])
us_ports_imports_by_cty_2018= us_ports_imports_by_cty_2018.drop(index = ["EURO AREA"])
us_ports_imports_by_cty_2018= us_ports_imports_by_cty_2018.drop(index = ["OPEC"])
us_ports_imports_by_cty_2018= us_ports_imports_by_cty_2018.drop(index = ["ASEAN"])
us_ports_imports_by_cty_2018= us_ports_imports_by_cty_2018.drop(index = ["SOUTH AMERICA"])
us_ports_imports_by_cty_2018= us_ports_imports_by_cty_2018.drop(index = ["AFRICA"])
us_ports_imports_by_cty_2018= us_ports_imports_by_cty_2018.drop(index = ["CENTRAL AMERICA"])
us_ports_imports_by_cty_2018= us_ports_imports_by_cty_2018.drop(index = ["APEC"])
us_ports_imports_by_cty_2018= us_ports_imports_by_cty_2018.drop(index = ["TOTAL FOR ALL COUNTRIES"])

#2019
us_ports_imports_by_cty_2019 = us_ports_imports_by_cty_2020.drop(index = ["OECD"])
us_ports_imports_by_cty_2019= us_ports_imports_by_cty_2019.drop(index = ["ASIA"])
us_ports_imports_by_cty_2019= us_ports_imports_by_cty_2019.drop(index = ["PACIFIC RIM COUNTRIES"])   
us_ports_imports_by_cty_2019= us_ports_imports_by_cty_2019.drop(index = ["NATO"])
us_ports_imports_by_cty_2019= us_ports_imports_by_cty_2019.drop(index = ["NORTH AMERICA"])
us_ports_imports_by_cty_2019= us_ports_imports_by_cty_2019.drop(index = ["NAFTA"])
us_ports_imports_by_cty_2019= us_ports_imports_by_cty_2019.drop(index = ["EUROPE"])
us_ports_imports_by_cty_2019= us_ports_imports_by_cty_2019.drop(index = ["TWENTY LATIN AMERICAN REPUBLICS"])
us_ports_imports_by_cty_2019= us_ports_imports_by_cty_2019.drop(index = ["LAFTA"])
us_ports_imports_by_cty_2019= us_ports_imports_by_cty_2019.drop(index = ["EUROPEAN UNION"])
us_ports_imports_by_cty_2019= us_ports_imports_by_cty_2019.drop(index = ["EURO AREA"])
us_ports_imports_by_cty_2019= us_ports_imports_by_cty_2019.drop(index = ["TOTAL FOR ALL COUNTRIES"])
us_ports_imports_by_cty_2019= us_ports_imports_by_cty_2019.drop(index = ["ASEAN"])
us_ports_imports_by_cty_2019= us_ports_imports_by_cty_2019.drop(index = ["SOUTH AMERICA"])
us_ports_imports_by_cty_2019= us_ports_imports_by_cty_2019.drop(index = ["AFRICA"])
us_ports_imports_by_cty_2019= us_ports_imports_by_cty_2019.drop(index = ["CENTRAL AMERICA"])
us_ports_imports_by_cty_2019= us_ports_imports_by_cty_2019.drop(index = ["APEC"])

#2020
us_ports_imports_by_cty_2020 = us_ports_imports_by_cty_2020.drop(index = ["OECD"])
us_ports_imports_by_cty_2020= us_ports_imports_by_cty_2020.drop(index = ["ASIA"])
us_ports_imports_by_cty_2020= us_ports_imports_by_cty_2020.drop(index = ["PACIFIC RIM COUNTRIES"])   
us_ports_imports_by_cty_2020= us_ports_imports_by_cty_2020.drop(index = ["NATO"])
us_ports_imports_by_cty_2020= us_ports_imports_by_cty_2020.drop(index = ["NORTH AMERICA"])
us_ports_imports_by_cty_2020= us_ports_imports_by_cty_2020.drop(index = ["NAFTA"])
us_ports_imports_by_cty_2020= us_ports_imports_by_cty_2020.drop(index = ["EUROPE"])
us_ports_imports_by_cty_2020= us_ports_imports_by_cty_2020.drop(index = ["TWENTY LATIN AMERICAN REPUBLICS"])
us_ports_imports_by_cty_2020= us_ports_imports_by_cty_2020.drop(index = ["LAFTA"])
us_ports_imports_by_cty_2020= us_ports_imports_by_cty_2020.drop(index = ["EUROPEAN UNION"])
us_ports_imports_by_cty_2020= us_ports_imports_by_cty_2020.drop(index = ["EURO AREA"])
us_ports_imports_by_cty_2020= us_ports_imports_by_cty_2020.drop(index = ["TOTAL FOR ALL COUNTRIES"])
us_ports_imports_by_cty_2020= us_ports_imports_by_cty_2020.drop(index = ["ASEAN"])
us_ports_imports_by_cty_2020= us_ports_imports_by_cty_2020.drop(index = ["SOUTH AMERICA"])
us_ports_imports_by_cty_2020= us_ports_imports_by_cty_2020.drop(index = ["AFRICA"])
us_ports_imports_by_cty_2020= us_ports_imports_by_cty_2020.drop(index = ["CENTRAL AMERICA"])
us_ports_imports_by_cty_2020= us_ports_imports_by_cty_2020.drop(index = ["APEC"])

#2021
us_ports_imports_by_cty_2021 = us_ports_imports_by_cty_2021.drop(index = ["OECD"])
us_ports_imports_by_cty_2021 = us_ports_imports_by_cty_2021.drop(index = ["ASIA"])
us_ports_imports_by_cty_2021 = us_ports_imports_by_cty_2021.drop(index = ["PACIFIC RIM COUNTRIES"])
us_ports_imports_by_cty_2021 = us_ports_imports_by_cty_2021.drop(index = ["NATO"])
us_ports_imports_by_cty_2021 = us_ports_imports_by_cty_2021.drop(index = ["NORTH AMERICA"])
us_ports_imports_by_cty_2021 = us_ports_imports_by_cty_2021.drop(index = ["NAFTA"])
us_ports_imports_by_cty_2021 = us_ports_imports_by_cty_2021.drop(index = ["EUROPE"])
us_ports_imports_by_cty_2021 = us_ports_imports_by_cty_2021.drop(index = ["TWENTY LATIN AMERICAN REPUBLICS"])
us_ports_imports_by_cty_2021 = us_ports_imports_by_cty_2021.drop(index = ["LAFTA"])
us_ports_imports_by_cty_2021 = us_ports_imports_by_cty_2021.drop(index = ["EUROPEAN UNION"])
us_ports_imports_by_cty_2021 = us_ports_imports_by_cty_2021.drop(index = ["EURO AREA"])
us_ports_imports_by_cty_2021 = us_ports_imports_by_cty_2021.drop(index = ["TOTAL FOR ALL COUNTRIES"])
us_ports_imports_by_cty_2021 = us_ports_imports_by_cty_2021.drop(index = ["ASEAN"])
us_ports_imports_by_cty_2021 = us_ports_imports_by_cty_2021.drop(index = ["SOUTH AMERICA"])
us_ports_imports_by_cty_2021 = us_ports_imports_by_cty_2021.drop(index = ["AFRICA"])
us_ports_imports_by_cty_2021 = us_ports_imports_by_cty_2021.drop(index = ["CENTRAL AMERICA"])
us_ports_imports_by_cty_2021 = us_ports_imports_by_cty_2021.drop(index = ["APEC"])

#202
us_ports_imports_by_cty_2022 = us_ports_imports_by_cty_2022.drop(index = ["OECD"])
us_ports_imports_by_cty_2022 = us_ports_imports_by_cty_2022.drop(index = ["ASIA"])
us_ports_imports_by_cty_2022 = us_ports_imports_by_cty_2022.drop(index = ["PACIFIC RIM COUNTRIES"])
us_ports_imports_by_cty_2022 = us_ports_imports_by_cty_2022.drop(index = ["NATO"])
us_ports_imports_by_cty_2022 = us_ports_imports_by_cty_2022.drop(index = ["NORTH AMERICA"])
us_ports_imports_by_cty_2022 = us_ports_imports_by_cty_2022.drop(index = ["NAFTA"])
us_ports_imports_by_cty_2022 = us_ports_imports_by_cty_2022.drop(index = ["EUROPE"])
us_ports_imports_by_cty_2022 = us_ports_imports_by_cty_2022.drop(index = ["TWENTY LATIN AMERICAN REPUBLICS"])
us_ports_imports_by_cty_2022 = us_ports_imports_by_cty_2022.drop(index = ["LAFTA"])
us_ports_imports_by_cty_2022 = us_ports_imports_by_cty_2022.drop(index = ["EUROPEAN UNION"])
us_ports_imports_by_cty_2022 = us_ports_imports_by_cty_2022.drop(index = ["EURO AREA"])

us_ports_imports_by_cty_2022 = us_ports_imports_by_cty_2022.drop(index = ["ASEAN"])
us_ports_imports_by_cty_2022 = us_ports_imports_by_cty_2022.drop(index = ["SOUTH AMERICA"])
us_ports_imports_by_cty_2022 = us_ports_imports_by_cty_2022.drop(index = ["AFRICA"])
us_ports_imports_by_cty_2022 = us_ports_imports_by_cty_2022.drop(index = ["CENTRAL AMERICA"])
us_ports_imports_by_cty_2022 = us_ports_imports_by_cty_2022.drop(index = ["APEC"])
us_ports_imports_by_cty_2022 = us_ports_imports_by_cty_2022.drop(index = ["TOTAL FOR ALL COUNTRIES"])
us_ports_imports_by_cty_2022

0                      CTY_CODE    ALL_VAL_YR     time
CTY_NAME
CAFTA-DR                   0017   35649714255  2022-12
CACM                       0028   28742055974  2022-12
GREENLAND                  1010      36193457  2022-12
CANADA                     1220  436561525548  2022-12
ST PIERRE AND MIQUELON     1610         18411  2022-12
...                         ...           ...      ...
ZAMBIA                     7940     135254441  2022-12
ESWATINI                   7950      22435037  2022-12
ZIMBABWE                   7960      86509488  2022-12
MALAWI                     7970      54005871  2022-12
LESOTHO                    7990     349542302  2022-12

[236 rows x 3 columns]

In [13]:
#concat the data frames
us_ports_imports_by_cty_2013_to_2022 = pd.concat([us_ports_imports_by_cty_2013,us_ports_imports_by_cty_2014,us_ports_imports_by_cty_2015,us_ports_imports_by_cty_2016,us_ports_imports_by_cty_2017,us_ports_imports_by_cty_2018,us_ports_imports_by_cty_2019,us_ports_imports_by_cty_2020,us_ports_imports_by_cty_2021,us_ports_imports_by_cty_2022])

#drop all that arent countries

us_ports_imports_by_cty_2013_to_2022

0                 CTY_CODE ALL_VAL_YR     time
CTY_NAME
NEW CALEDONIA         6412   69561109  2013-12
WALLIS AND FUTUNA     6413     296015  2013-12
FRENCH POLYNESIA      6414   36492874  2013-12
MARSHALL ISLANDS      6810   16965963  2013-12
MICRONESIA            6820    1786725  2013-12
...                    ...        ...      ...
ZAMBIA                7940  135254441  2022-12
ESWATINI              7950   22435037  2022-12
ZIMBABWE              7960   86509488  2022-12
MALAWI                7970   54005871  2022-12
LESOTHO               7990  349542302  2022-12

[2353 rows x 3 columns]

In [14]:
#What are the top 3 US ports by total value?
# convert the values into a integer 
us_ports_imports_by_cty_2013_to_2022['ALL_VAL_YR'] = pd.to_numeric(us_ports_imports_by_cty_2013_to_2022['ALL_VAL_YR'])

# Now, group by CTY_NAME and sum the ALL_VAL_YR values
grouped_data = us_ports_imports_by_cty_2013_to_2022.groupby('CTY_NAME')['ALL_VAL_YR'].sum()
grouped_data = pd.DataFrame(grouped_data)
# Sort and display the top 3

grouped_data
top_3_countries = grouped_data.sort_values(by = "ALL_VAL_YR", ascending=False).head(3)
top_3_countries

             ALL_VAL_YR
CTY_NAME
CHINA     4803895145408
MEXICO    3306884460703
CANADA    3207346879457

In [15]:
# were these countries the top 3 each year?
# us_ports_imports_by_cty_2013,us_ports_imports_by_cty_2014,us_ports_imports_by_cty_2015,us_ports_imports_by_cty_2016,us_ports_imports_by_cty_2017,us_ports_imports_by_cty_2018,us_ports_imports_by_cty_2019,us_ports_imports_by_cty_2020,us_ports_imports_by_cty_2021,us_ports_imports_by_cty_2022
#2013
us_ports_imports_by_cty_2013['ALL_VAL_YR'] = pd.to_numeric(us_ports_imports_by_cty_2013['ALL_VAL_YR'])
grouped_data_for_2013 = us_ports_imports_by_cty_2013.groupby('CTY_NAME')['ALL_VAL_YR'].max()
top_3_countries_for_2013 = grouped_data_for_2013.sort_values(ascending=False).head(3)


#2014
us_ports_imports_by_cty_2014['ALL_VAL_YR'] = pd.to_numeric(us_ports_imports_by_cty_2014['ALL_VAL_YR'])
grouped_data_for_2014 = us_ports_imports_by_cty_2014.groupby('CTY_NAME')['ALL_VAL_YR'].max()
top_3_countries_for_2014 = grouped_data_for_2014.sort_values(ascending=False).head(3)

#2015
us_ports_imports_by_cty_2015['ALL_VAL_YR'] = pd.to_numeric(us_ports_imports_by_cty_2015['ALL_VAL_YR'])
grouped_data_for_2015 = us_ports_imports_by_cty_2015.groupby('CTY_NAME')['ALL_VAL_YR'].max()
top_3_countries_for_2015 = grouped_data_for_2015.sort_values(ascending=False).head(3)


#2016
us_ports_imports_by_cty_2016['ALL_VAL_YR'] = pd.to_numeric(us_ports_imports_by_cty_2016['ALL_VAL_YR'])
grouped_data_for_2016 = us_ports_imports_by_cty_2016.groupby('CTY_NAME')['ALL_VAL_YR'].max()
top_3_countries_for_2016 = grouped_data_for_2016.sort_values(ascending=False).head(3)

#2017
us_ports_imports_by_cty_2017['ALL_VAL_YR'] = pd.to_numeric(us_ports_imports_by_cty_2017['ALL_VAL_YR'])
grouped_data_for_2017 = us_ports_imports_by_cty_2017.groupby('CTY_NAME')['ALL_VAL_YR'].max()
top_3_countries_for_2017 = grouped_data_for_2017.sort_values(ascending=False).head(3)

#2018
us_ports_imports_by_cty_2018['ALL_VAL_YR'] = pd.to_numeric(us_ports_imports_by_cty_2018['ALL_VAL_YR'])
grouped_data_for_2018 = us_ports_imports_by_cty_2018.groupby('CTY_NAME')['ALL_VAL_YR'].max()
top_3_countries_for_2018 = grouped_data_for_2018.sort_values(ascending=False).head(3)


#2019
us_ports_imports_by_cty_2019['ALL_VAL_YR'] = pd.to_numeric(us_ports_imports_by_cty_2019['ALL_VAL_YR'])
grouped_data_for_2019 = us_ports_imports_by_cty_2019.groupby('CTY_NAME')['ALL_VAL_YR'].max()
top_3_countries_for_2019 = grouped_data_for_2019.sort_values(ascending=False).head(3)


#2020
us_ports_imports_by_cty_2020['ALL_VAL_YR'] = pd.to_numeric(us_ports_imports_by_cty_2020['ALL_VAL_YR'])
grouped_data_for_2020 = us_ports_imports_by_cty_2020.groupby('CTY_NAME')['ALL_VAL_YR'].max()
top_3_countries_for_2020 = grouped_data_for_2020.sort_values(ascending=False).head(3)
top_3_countries_for_2020

#2021
us_ports_imports_by_cty_2021['ALL_VAL_YR'] = pd.to_numeric(us_ports_imports_by_cty_2021['ALL_VAL_YR'])
grouped_data_for_2021 = us_ports_imports_by_cty_2021.groupby('CTY_NAME')['ALL_VAL_YR'].max()
top_3_countries_for_2021 = grouped_data_for_2021.sort_values(ascending=False).head(3)


#2022
us_ports_imports_by_cty_2022['ALL_VAL_YR'] = pd.to_numeric(us_ports_imports_by_cty_2022['ALL_VAL_YR'])
grouped_data_for_2022 = us_ports_imports_by_cty_2022.groupby('CTY_NAME')['ALL_VAL_YR'].max()
top_3_countries_for_2022 = grouped_data_for_2022.sort_values(ascending=False).head(3)

In [16]:
# show the countries that had the most imports in USD per year
print(f"The top 3 countries in for 2013 are: {top_3_countries_for_2013}")
print(f"The top 3 countries in for 2014 are: {top_3_countries_for_2014}")
print(f"The top 3 countries in for 2015 are: {top_3_countries_for_2015}")
print(f"The top 3 countries in for 2016 are: {top_3_countries_for_2016}")
print(f"The top 3 countries in for 2017 are: {top_3_countries_for_2017}")
print(f"The top 3 countries in for 2018 are: {top_3_countries_for_2018}")
print(f"The top 3 countries in for 2019 are: {top_3_countries_for_2019}")
print(f"The top 3 countries in for 2020 are: {top_3_countries_for_2020}")
print(f"The top 3 countries in for 2021 are: {top_3_countries_for_2021}")
print(f"The top 3 countries in for 2023 are: {top_3_countries_for_2022}")

The top 3 countries in for 2013 are: CTY_NAME
CHINA     440430019592
CANADA    332503645324
MEXICO    280556040242
Name: ALL_VAL_YR, dtype: int64
The top 3 countries in for 2014 are: CTY_NAME
CHINA     468474894856
CANADA    349286122826
MEXICO    295729962846
Name: ALL_VAL_YR, dtype: int64
The top 3 countries in for 2015 are: CTY_NAME
CHINA     483201655364
MEXICO    296433325024
CANADA    296305080863
Name: ALL_VAL_YR, dtype: int64
The top 3 countries in for 2016 are: CTY_NAME
CHINA     462419991603
MEXICO    293500606660
CANADA    277719813481
Name: ALL_VAL_YR, dtype: int64
The top 3 countries in for 2017 are: CTY_NAME
CHINA     505165098057
MEXICO    312666740496
CANADA    299065421162
Name: ALL_VAL_YR, dtype: int64
The top 3 countries in for 2018 are: CTY_NAME
CHINA     538514158526
MEXICO    343680540510
CANADA    318574772746
Name: ALL_VAL_YR, dtype: int64
The top 3 countries in for 2019 are: CTY_NAME
CHINA     432548018651
MEXICO    323476917991
CANADA    270025523613
Name: ALL_VAL_YR, dtype: int64
The top 3 countries in for 2020 are: CTY_NAME
CHINA     432548018651
MEXICO    323476917991
CANADA    270025523613
Name: ALL_VAL_YR, dtype: int64
The top 3 countries in for 2021 are: CTY_NAME
CHINA     504286202159
MEXICO    382588717029
CANADA    357279450281
Name: ALL_VAL_YR, dtype: int64
The top 3 countries in for 2023 are: CTY_NAME
CHINA     536307087949
MEXICO    454774691914
CANADA    436561525548
Name: ALL_VAL_YR, dtype: int64

In [17]:
# canada imported more than mexico  only during the years of 2013 and 2014

In [18]:
# Were there any years with an overall decrease in total import or export value? 

grouped_data_2 = us_ports_imports_by_cty_2013_to_2022.groupby('time')['ALL_VAL_YR'].sum()
grouped_data_2 = pd.DataFrame(grouped_data_2)
grouped_data_2

            ALL_VAL_YR
time
2013-12  2337205579089
2014-12  2423791959001
2015-12  2307278565689
2016-12  2242798371753
2017-12  2396814030861
2018-12  2595696327457
2020-12  4785353209724
2021-12  2900188307696
2022-12  3328976095745

In [19]:
# from 2014 - 2015 there was a 1 hundred billion (116513393312)  dollar decrease
# from 2015 - 2016 there was a 6.4 billion (64480193936)  dollar decrease
#from 2020 - 2021 there was a 1.8 trillion (1885164900000) dollar decrease

In [20]:
#What was the Y/Y (year-over-year) change in total value?
grouped_data_2.pct_change()

         ALL_VAL_YR
time
2013-12         NaN
2014-12    0.037047
2015-12   -0.048071
2016-12   -0.027946
2017-12    0.068671
2018-12    0.082978
2020-12    0.843572
2021-12   -0.393945
2022-12    0.147848

In [21]:
# 2015 , 2016 and 2021 had a decrease in total import value in USD

In [22]:
#What are the top 3 countries by import value? 
us_ports_imports_by_cty_2013_to_2022['ALL_VAL_YR'] = pd.to_numeric(us_ports_imports_by_cty_2013_to_2022['ALL_VAL_YR'])

# Now, group by CTY_NAME and sum the ALL_VAL_YR values
grouped_data = us_ports_imports_by_cty_2013_to_2022.groupby('CTY_NAME')['ALL_VAL_YR'].sum()
grouped_data = pd.DataFrame(grouped_data)
# Sort and display the top 3


top_3_countries = grouped_data.sort_values(by = "ALL_VAL_YR", ascending=False).head(3)
top_3_countries

             ALL_VAL_YR
CTY_NAME
CHINA     4803895145408
MEXICO    3306884460703
CANADA    3207346879457

In [23]:
#2013 COMMODITY for Mexico
r = requests.get("https://api.census.gov/data/timeseries/intltrade/imports/hs?get=I_COMMODITY,I_COMMODITY_SDESC,GEN_VAL_YR&time=2013-12&CTY_CODE=2010")
data = r.json()
#fix the index
all_commodities_2013 = pd.DataFrame(data)
all_commodities_2013.columns = all_commodities_2013.iloc[0]
all_commodities_2013 = all_commodities_2013[1:]
all_commodities_2013 = all_commodities_2013.rename(columns={'GEN_VAL_YR': 'ALL_VAL_YR'})
all_commodities_2013.set_index('I_COMMODITY', inplace=True)

#sort the dataframe

all_commodities_2013['ALL_VAL_YR'] = pd.to_numeric(all_commodities_2013['ALL_VAL_YR'])
all_commodities_2013 = all_commodities_2013.sort_values(['ALL_VAL_YR'], ascending=[False])
all_commodities_2013 = all_commodities_2013.drop(index = ["-"])
top_commodity_2013 = all_commodities_2013.head(1)
top_commodity_2013

,I_COMMODITY_SDESC,ALL_VAL_YR,time,CTY_CODE
I_COMMODITY,,,,
87,"VEHICLES, EXCEPT RAILWAY OR TRAMWAY, AND PARTS...",59597907014,2013-12,2010

In [24]:
#2014 COMMODITY for Mexico
r = requests.get("https://api.census.gov/data/timeseries/intltrade/imports/hs?get=I_COMMODITY,I_COMMODITY_SDESC,GEN_VAL_YR&time=2014-12&CTY_CODE=2010")
data = r.json()
#fix the index
all_commodities_2014 = pd.DataFrame(data)
all_commodities_2014.columns = all_commodities_2014.iloc[0]
all_commodities_2014 = all_commodities_2014[1:]
all_commodities_2014 = all_commodities_2014.rename(columns={'GEN_VAL_YR': 'ALL_VAL_YR'})
all_commodities_2014.set_index('I_COMMODITY', inplace=True)

#sort the dataframe

all_commodities_2014['ALL_VAL_YR'] = pd.to_numeric(all_commodities_2014['ALL_VAL_YR'])
all_commodities_2014 = all_commodities_2014.sort_values(['ALL_VAL_YR'], ascending=[False])
all_commodities_2014 = all_commodities_2014.drop(index = ["-"])
top_commodity_2014 = all_commodities_2014.head(1)
top_commodity_2014

,I_COMMODITY_SDESC,ALL_VAL_YR,time,CTY_CODE
I_COMMODITY,,,,
87,"VEHICLES, EXCEPT RAILWAY OR TRAMWAY, AND PARTS...",68041013031,2014-12,2010

In [25]:
#2015 COMMODITY for Mexico
r = requests.get("https://api.census.gov/data/timeseries/intltrade/imports/hs?get=I_COMMODITY,I_COMMODITY_SDESC,GEN_VAL_YR&time=2015-12&CTY_CODE=2010")
data = r.json()
#fix the index
all_commodities_for_mexico_2015 = pd.DataFrame(data)
all_commodities_for_mexico_2015.columns = all_commodities_for_mexico_2015.iloc[0]
all_commodities_for_mexico_2015 = all_commodities_for_mexico_2015[1:]
all_commodities_for_mexico_2015 = all_commodities_for_mexico_2015.rename(columns={'GEN_VAL_YR': 'ALL_VAL_YR'})
all_commodities_for_mexico_2015.set_index('I_COMMODITY', inplace=True)

#sort the dataframe

all_commodities_for_mexico_2015['ALL_VAL_YR'] = pd.to_numeric(all_commodities_for_mexico_2015['ALL_VAL_YR'])
all_commodities_for_mexico_2015 = all_commodities_for_mexico_2015.sort_values(['ALL_VAL_YR'], ascending=[False])
all_commodities_for_mexico_2015 = all_commodities_for_mexico_2015.drop(index = ["-"])
all_commodities_for_mexico_2015 = all_commodities_for_mexico_2015.head(1)
all_commodities_for_mexico_2015

,I_COMMODITY_SDESC,ALL_VAL_YR,time,CTY_CODE
I_COMMODITY,,,,
87,"VEHICLES, EXCEPT RAILWAY OR TRAMWAY, AND PARTS...",74685049597,2015-12,2010

In [71]:
#2016 COMMODITY for Mexico
r = requests.get("https://api.census.gov/data/timeseries/intltrade/imports/hs?get=I_COMMODITY,I_COMMODITY_SDESC,GEN_VAL_YR&time=2016-12&CTY_CODE=2010")
data = r.json()
#fix the index
all_commodities_for_mexico_2016 = pd.DataFrame(data)
all_commodities_for_mexico_2016.columns = all_commodities_for_mexico_2016.iloc[0]
all_commodities_for_mexico_2016 = all_commodities_for_mexico_2016[1:]
all_commodities_for_mexico_2016 = all_commodities_for_mexico_2016.rename(columns={'GEN_VAL_YR': 'ALL_VAL_YR'})
all_commodities_for_mexico_2016.set_index('I_COMMODITY', inplace=True)

#sort the dataframe

all_commodities_for_mexico_2016['ALL_VAL_YR'] = pd.to_numeric(all_commodities_for_mexico_2016['ALL_VAL_YR'])
all_commodities_for_mexico_2016 = all_commodities_for_mexico_2016.sort_values(['ALL_VAL_YR'], ascending=[False])
all_commodities_for_mexico_2016 = all_commodities_for_mexico_2016.drop(index = ["-"])
top_commodity__for_mexico_2016 = all_commodities_for_mexico_2016.head(1)

In [69]:
#2017 COMMODITY for Mexico
r = requests.get("https://api.census.gov/data/timeseries/intltrade/imports/hs?get=I_COMMODITY,I_COMMODITY_SDESC,GEN_VAL_YR&time=2017-12&CTY_CODE=2010")
data = r.json()
#fix the index
all_commodities_for_mexico_2017 = pd.DataFrame(data)
all_commodities_for_mexico_2017.columns = all_commodities_for_mexico_2017.iloc[0]
all_commodities_for_mexico_2017 = all_commodities_for_mexico_2017[1:]
all_commodities_for_mexico_2017 = all_commodities_for_mexico_2017.rename(columns={'GEN_VAL_YR': 'ALL_VAL_YR'})
all_commodities_for_mexico_2017.set_index('I_COMMODITY', inplace=True)

#sort the dataframe
all_commodities_for_mexico_2017['ALL_VAL_YR'] = pd.to_numeric(all_commodities_for_mexico_2017['ALL_VAL_YR'])
all_commodities_for_mexico_2017 = all_commodities_for_mexico_2017.sort_values(['ALL_VAL_YR'], ascending=[False])
all_commodities_for_mexico_2017 = all_commodities_for_mexico_2017.drop(index = ["-"])
top_commodity__for_mexico_2017 = all_commodities_for_mexico_2017.head(1)

In [66]:
#2018 COMMODITY for Mexico
r = requests.get("https://api.census.gov/data/timeseries/intltrade/imports/hs?get=I_COMMODITY,I_COMMODITY_SDESC,GEN_VAL_YR&time=2018-12&CTY_CODE=2010")
data = r.json()
#fix the index
all_commodities_for_mexico_2018 = pd.DataFrame(data)
all_commodities_for_mexico_2018.columns = all_commodities_for_mexico_2018.iloc[0]
all_commodities_for_mexico_2018 = all_commodities_for_mexico_2018[1:]
all_commodities_for_mexico_2018 = all_commodities_for_mexico_2018.rename(columns={'GEN_VAL_YR': 'ALL_VAL_YR'})
all_commodities_for_mexico_2018.set_index('I_COMMODITY', inplace=True)

#sort the dataframe
all_commodities_for_mexico_2018['ALL_VAL_YR'] = pd.to_numeric(all_commodities_for_mexico_2018['ALL_VAL_YR'])
all_commodities_for_mexico_2018 = all_commodities_for_mexico_2018.sort_values(['ALL_VAL_YR'], ascending=[False])
all_commodities_for_mexico_2018 = all_commodities_for_mexico_2018.drop(index = ["-"])
top_commodity__for_mexico_2018 = all_commodities_for_mexico_2018.head(1)

In [64]:
#2019 COMMODITY for Mexico
r = requests.get("https://api.census.gov/data/timeseries/intltrade/imports/hs?get=I_COMMODITY,I_COMMODITY_SDESC,GEN_VAL_YR&time=2019-12&CTY_CODE=2010")
data = r.json()
#fix the index
all_commodities_for_mexico_2019 = pd.DataFrame(data)
all_commodities_for_mexico_2019.columns = all_commodities_for_mexico_2019.iloc[0]
all_commodities_for_mexico_2019 = all_commodities_for_mexico_2019[1:]
all_commodities_for_mexico_2019 = all_commodities_for_mexico_2019.rename(columns={'GEN_VAL_YR': 'ALL_VAL_YR'})
all_commodities_for_mexico_2019.set_index('I_COMMODITY', inplace=True)

#sort the dataframe
all_commodities_for_mexico_2019['ALL_VAL_YR'] = pd.to_numeric(all_commodities_for_mexico_2019['ALL_VAL_YR'])
all_commodities_for_mexico_2019 = all_commodities_for_mexico_2019.sort_values(['ALL_VAL_YR'], ascending=[False])
all_commodities_for_mexico_2019 = all_commodities_for_mexico_2019.drop(index = ["-"])
top_commodity__for_mexico_2019 = all_commodities_for_mexico_2019.head(1)

In [61]:
#2020 COMMODITY for Mexico
r = requests.get("https://api.census.gov/data/timeseries/intltrade/imports/hs?get=I_COMMODITY,I_COMMODITY_SDESC,GEN_VAL_YR&time=2020-12&CTY_CODE=2010")
data = r.json()
#fix the index
all_commodities_for_mexico_2020 = pd.DataFrame(data)
all_commodities_for_mexico_2020.columns = all_commodities_for_mexico_2020.iloc[0]
all_commodities_for_mexico_2020 = all_commodities_for_mexico_2020[1:]
all_commodities_for_mexico_2020 = all_commodities_for_mexico_2020.rename(columns={'GEN_VAL_YR': 'ALL_VAL_YR'})
all_commodities_for_mexico_2020.set_index('I_COMMODITY', inplace=True)

#sort the dataframe
all_commodities_for_mexico_2020['ALL_VAL_YR'] = pd.to_numeric(all_commodities_for_mexico_2020['ALL_VAL_YR'])
all_commodities_for_mexico_2020 = all_commodities_for_mexico_2020.sort_values(['ALL_VAL_YR'], ascending=[False])
all_commodities_for_mexico_2020 = all_commodities_for_mexico_2020.drop(index = ["-"])
top_commodity__for_mexico_2020 = all_commodities_for_mexico_2020.head(1)

In [58]:
#2021 COMMODITY for Mexico
r = requests.get("https://api.census.gov/data/timeseries/intltrade/imports/hs?get=I_COMMODITY,I_COMMODITY_SDESC,GEN_VAL_YR&time=2021-12&CTY_CODE=2010")
data = r.json()
#fix the index
all_commodities_for_mexico_2021 = pd.DataFrame(data)
all_commodities_for_mexico_2021.columns = all_commodities_for_mexico_2021.iloc[0]
all_commodities_for_mexico_2021 = all_commodities_for_mexico_2021[1:]
all_commodities_for_mexico_2021 = all_commodities_for_mexico_2021.rename(columns={'GEN_VAL_YR': 'ALL_VAL_YR'})
all_commodities_for_mexico_2021.set_index('I_COMMODITY', inplace=True)

#sort the dataframe
all_commodities_for_mexico_2021['ALL_VAL_YR'] = pd.to_numeric(all_commodities_for_mexico_2021['ALL_VAL_YR'])
all_commodities_for_mexico_2021 = all_commodities_for_mexico_2021.sort_values(['ALL_VAL_YR'], ascending=[False])
all_commodities_for_mexico_2021 = all_commodities_for_mexico_2021.drop(index = ["-"])
top_commodity_for_mexico_2021 = all_commodities_for_mexico_2021.head(1)

In [57]:
#2022 COMMODITY for Mexico
r = requests.get("https://api.census.gov/data/timeseries/intltrade/imports/hs?get=I_COMMODITY,I_COMMODITY_SDESC,GEN_VAL_YR&time=2022-12&CTY_CODE=2010")
data = r.json()
#fix the index
all_commodities_for_mexico_2022 = pd.DataFrame(data)
all_commodities_for_mexico_2022.columns = all_commodities_for_mexico_2022.iloc[0]
all_commodities_for_mexico_2022 = all_commodities_for_mexico_2022[1:]
all_commodities_for_mexico_2022 = all_commodities_for_mexico_2022.rename(columns={'GEN_VAL_YR': 'ALL_VAL_YR'})
all_commodities_for_mexico_2022.set_index('I_COMMODITY', inplace=True)
all_commodities_for_mexico_2022
#sort the dataframe
all_commodities_for_mexico_2022['ALL_VAL_YR'] = pd.to_numeric(all_commodities_for_mexico_2022['ALL_VAL_YR'])
all_commodities_for_mexico_2022 = all_commodities_for_mexico_2022.sort_values(['ALL_VAL_YR'], ascending=[False])
all_commodities_for_mexico_2022 = all_commodities_for_mexico_2022.drop(index = ["-"])
top_commodity_for_mexico_2022 = all_commodities_for_mexico_2022.head(1)

In [ ]:
#2013 COMMODITY for China
r = requests.get("https://api.census.gov/data/timeseries/intltrade/imports/hs?get=I_COMMODITY,I_COMMODITY_SDESC,GEN_VAL_YR&time=2013-12&CTY_CODE=5700")
data = r.json()
#fix the index
all_commodities_2022 = pd.DataFrame(data)
all_commodities_2022.columns = all_commodities_2022.iloc[0]
all_commodities_2022 = all_commodities_2022[1:]
all_commodities_2022 = all_commodities_2022.rename(columns={'GEN_VAL_YR': 'ALL_VAL_YR'})
all_commodities_2022.set_index('I_COMMODITY', inplace=True)

#sort the dataframe
all_commodities_2022['ALL_VAL_YR'] = pd.to_numeric(all_commodities_2022['ALL_VAL_YR'])
all_commodities_2022 = all_commodities_2022.sort_values(['ALL_VAL_YR'], ascending=[False])
all_commodities_2022 = all_commodities_2022.drop(index = ["-"])
top_commodity_2022 = all_commodities_2022.head(1)
top_commodity_2022

In [45]:
top_commodities_for_mexico_from_2013_to_2022 = pd.concat([top_commodity_2013,top_commodity_2014,top_commodity_2015,top_commodity_2016,top_commodity_2017,top_commodity_2018,top_commodity_2019,top_commodity_2020,top_commodity_2021,top_commodity_2022])


top_commodities_for_mexico_from_2013_to_2022

,I_COMMODITY_SDESC,ALL_VAL_YR,time,CTY_CODE
I_COMMODITY,,,,
87,"VEHICLES, EXCEPT RAILWAY OR TRAMWAY, AND PARTS...",59597907014,2013-12,2010
87,"VEHICLES, EXCEPT RAILWAY OR TRAMWAY, AND PARTS...",68041013031,2014-12,2010
87,"VEHICLES, EXCEPT RAILWAY OR TRAMWAY, AND PARTS...",74685049597,2015-12,2010
87,"VEHICLES, EXCEPT RAILWAY OR TRAMWAY, AND PARTS...",74734142772,2016-12,2010
87,"VEHICLES, EXCEPT RAILWAY OR TRAMWAY, AND PARTS...",83501968461,2017-12,2010
87,"VEHICLES, EXCEPT RAILWAY OR TRAMWAY, AND PARTS...",92974416517,2018-12,2010
87,"VEHICLES, EXCEPT RAILWAY OR TRAMWAY, AND PARTS...",101140678848,2019-12,2010
87,"VEHICLES, EXCEPT RAILWAY OR TRAMWAY, AND PARTS...",82478748912,2020-12,2010
87,"VEHICLES, EXCEPT RAILWAY OR TRAMWAY, AND PARTS...",93374118845,2021-12,2010
87,"VEHICLES, EXCEPT RAILWAY OR TRAMWAY, AND PARTS...",111108449944,2022-12,2010

In [47]:
total_value_of_top_commodity_for_mexico = top_commodities_for_mexico_from_2013_to_2022['ALL_VAL_YR'].sum()
total_value_of_top_commodity_for_mexico

841636493941